### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by EBKlerman** [DennisDean/SpectralTrainFig#1]
Hi,
This is a duplicate of questions about starting to use the program left under Commit.
1) When we click to install the app, it asks us for the program to use to run the app. What do we do?

2) Will MATlab 2011b work or only 2013b?
3) We have edf files but they do not have edf.xml files. What do we do to run the program?

Thanks

**Comment by DennisDean** [comment]
Questions answered on the sleepdata.org forum.
